meta:
  title: Oğuzcan Demircan
  author: Oğuzcan Demircan
  owner: Oğuzcan Demircan
  generator: Oğuzcan Demircan
  # description: laravel, php, vuejs, javascript etc. my thinking about programming languages, frameworks, technologies, and various other things.
  description: laravel, php, vuejs, javascript vb. programlama dilleri, frameworkleri, teknolojileri ve diğer çeşitli alanlar hakkındaki bilgi, düşünce ve deneyimlerimi içeren blog.
  keywords: oguzcandemircan, oğuzcan demircan, laravel, developer, backend, php, yazılım, açık kaynak, software developer, open source, vue js, javascript, yazılım geliştirici, geliştirici

navs:
- name: anasayfa
  url: /

- name: makaleler
  url: /makaleler 

- name: etiketler
  url: /etiketler

- name: Hakkımda
  url: /hakkimda

social-network-links:
  twitter: oguzcandemircan
  github: oguzcandemircan
  gitlab: oguzcandemircan
  medium: oguzcandemircan
  linkedin: oguzcandemircan
  email: demircanoguzcan@gmail.com

disqus:
  active: true
  username: oguzcandemircan

loader: 
  active: false
  text: "Oğuzcan Demrican"

url: "https://oguzcandemircan.com"
permalink: :title
default_language: tr

author: 
  name: Oğuzcan Demircan
  image: /assets/images/oguzcan-demircan.jpg
  title: Software Developer

footer:
  text: © 2019 Oğuzcan Demircan All Rights Reserved

plugins:
  - jekyll-sitemap
